### ISSUE TITLE
in `process_call': undefined method `empty?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by kematy** [seattlerb/ruby_to_c#7]
require 'ruby_parser'
  require 'ruby_to_ruby_c'
  #require 'ruby_to_ansi_c'

  sexp1=RubyParser.new.parse(File.read('hello.rb') )
  puts sexp1.inspect
  r2c=RubyToRubyC.new
  c1    = r2c.process sexp1
  puts c1

I got errors  as following:

d:/Ruby25/lib/ruby/gems/2.5.0/gems/ruby2c-1.1.0/lib/ruby_to_ruby_c.rb:61:in `process_call': undefined method `empty?' for nil:NilClass (NoMethodError)
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:269:in `block (2 levels) in process'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:324:in `error_handler'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:268:in `block in process'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:388:in `in_context'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:245:in `process'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/ruby2c-1.1.0/lib/ruby_to_ruby_c.rb:292:in `block in make_function'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/ruby2c-1.1.0/lib/r2cenvironment.rb:46:in `scope'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/ruby2c-1.1.0/lib/ruby_to_ruby_c.rb:288:in `make_function'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/ruby2c-1.1.0/lib/ruby_to_ruby_c.rb:79:in `process_defn'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:269:in `block (2 levels) in process'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:324:in `error_handler'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:268:in `block in process'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:388:in `in_context'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:245:in `process'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/ruby2c-1.1.0/lib/ruby_to_ansi_c.rb:265:in `process_class'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:269:in `block (2 levels) in process'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:324:in `error_handler'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:268:in `block in process'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:388:in `in_context'
	from d:/Ruby25/lib/ruby/gems/2.5.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:245:in `process'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/ruby2c-1.1.0/demo/test.rb:8:in `<main>'
s(:class, :Hello, nil, s(:defn, :hello, s(:args), s(:call, nil, :puts, s(:str, "hello world"))), s(:defn, :main, s(:args), s(:call, nil, :hello), s(:return, s(:lit, 0))))
[Finished in 0.6s with exit code 1]

**Comment by zenspider** [comment]
Repro incomplete. I can't work with this. Because of it's age, I'm gonna close this. Reopen with a complete repro if you want.
