### ISSUE TITLE
Unable to activate ParseTree-3.0.9, because sexp_processor-4.9.0 conflicts with sexp_processor (~> 3.2.0)

### ISSUE THREAD

**Issue by kematy** [seattlerb/ruby_to_c#8]
d:/Ruby25/lib/ruby/2.5.0/rubygems/specification.rb:1466:in `block in activate_dependencies': can't satisfy 'sexp_processor (~> 3.2.0)', already activated 'sexp_processor-4.9.0' (Gem::LoadError)
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from d:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from D:/ruby-lab/rubytoc/RubyToC/test1.rb:2:in `<main>'
Unable to activate ParseTree-3.0.9, because sexp_processor-4.9.0 conflicts with sexp_processor (~> 3.2.0)
Unable to activate ParseTree-3.0.9, because sexp_processor-4.9.0 conflicts with sexp_processor (~> 3.2.0)

**Comment by zenspider** [comment]
ParseTree is long long loooong dead. You shouldn't even be bothering. Depending on what you want to do, you might want to look at ruby_parser instead.
